name: yarn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install yarn
      run: npm install yarn -g

    - name: Install dependencies
      run: yarn install

    - name: Run the tests
      run: yarn test

    - name: Build
      run: yarn run build
      
    # 部署到阿里云
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@main
      env:
        # 私钥
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # scp参数
        ARGS: "-rltgoDzvO --delete"
        # 源目录，编译后生成的文件目录
        SOURCE: "public/"
        # 服务器ip：换成你的服务器IP
        REMOTE_HOST: "8.141.159.53"
        # 用户
        REMOTE_USER: "bank"
        # 目标地址 你在服务器上部署代码的地方
        TARGET: "/www/wwwroot/orchestration.rinne.top"
        EXCLUDE: "/node_modules/"
